### ISSUE TITLE
Intellisense Documentation

### ISSUE THREAD

**Issue by Nick-Lucas** [Nick-Lucas/LimeBean#1]
Work on adding documentation comments to all user facing interfaces.

This should help when new users are picking up LimeBean

**Comment by Nick-Lucas** [comment]
#3 is a WIP for this

**Comment by Nick-Lucas** [comment]
#3 now completed, first draft.
Will be double checking and fixing any inaccuracies and grammar issues

**Comment by AlekseyMartynov** [comment]
Great! I'll read through the descriptions too, and let you know if I have any suggestions.

**Comment by Nick-Lucas** [comment]
Thanks! One thing I was a little vague on was the `.Key` methods. My educated guess has been these are there entirely for FluidMode configuration, as we normally get Keys from the database on load.

I'm also considering listing `.Find(...)` as deprecated, because I can't think of a situation where it would be better than `.FindIterator()`, especially with the fix I've put into #14.
In my testing `.FindIterator()` used about 2/3rds the RAM to run the same query, and that was before my fix which also removed all latency from the start of an operation.

**Comment by AlekseyMartynov** [comment]
`.Key` methods aren't tied to Fluid Mode. They are to configure which database columns are used for primary key. There's some info on the website https://nick-lucas.github.io/LimeBean/#primary-keys

As for `Find` vs `FindiIterator`, one big difference is that results of `Find` are cached. The rule is simple: `Find` for small collections, `FindIterator` for large.

**Comment by Nick-Lucas** [comment]
Hmmm it would surprise me if we couldn't handle this on the users behalf. MySql has `INFORMATION_SCHEMA` for instance. Need to dig into how Limebean handles keys.

Yup I noticed this. Iterator doesn't really need caching because lazy loading from reader is great. I've added advice on usage into the comments

**Comment by Nick-Lucas** [comment]
Merged in 7c4682a2cb77fcfe808f81058dce41012cefbb49
