### ISSUE TITLE
Allow a Bean to have its Fields iterated on

### ISSUE THREAD

**Issue by Nick-Lucas** [Nick-Lucas/LimeBean#13]
This can sometimes limit flexibility right now, as a Bean is a black box which you can only get things out of if you know they exist.

Suggest implementing IEnumerable on the Bean class, which should not be a breaking change. If it may be breaking then adding a ColumnIterator property which IS iterable would the next best thing

**Comment by AlekseyMartynov** [comment]
`IEnumerable` is not the best interface, because a bean is more a dictionary-like structure rather than a sequence. I remember that I wanted to add `IDictionary<string, object>` implementation, but decided not to do because this interface is too bloated.

Exposing `_props.Keys` as an `IEnumerable<string>` would be better.

**Comment by Nick-Lucas** [comment]
This makes sense. It won't be obvious to the user that a Bean is a Dictionary without looking at the source, so exposing anything directly on the bean is probably bad, and would bloat the Bean interface considerably with Linq.

We could expose `Bean.Columns`, I would argue as an `IEnumerable<BeanField>`?
This provides a simpler interface than exposing `_props` directly, and `BeanField` would just wrap a KeyValuePair. But it can provide accessor properties/methods (.ColumnName, .Data<T>) which are more in line with Limebean's style in name and usage - providing ConvertSafe<T> usage for the value.

This would also open the doors to a `BeanField.DataType` property/method, but I need to dig in and see if we already have the capability to determine the type of a variable after it's loaded from the database.

In this case I would aim to make BeanField a `struct` so it's fast during iteration, but rarely use these so need to check a struct can support everything I've just mentioned.

**Comment by AlekseyMartynov** [comment]
> This provides a simpler interface than exposing _props directly

I was talking about exposing `_props.Keys`, not `_props`

```
public IEnumerable<string> Something { get { return _props.Keys; } }
```

Then, iteration will look like this:
```
foreach(var name in bean.Something)
    Console.WriteLine(name + " = " + bean[name]);
```

**Comment by Nick-Lucas** [comment]
Sorry for the confusion, I was alluding back to my original idea in support of your idea. :sweat_smile: 

You may be right as the `string` approach is slightly less complex for the user. 
The one drawback to your approach would be having to lookup the field in `_props` on every iteration, whereas return a BeanField would give direct access inside the original iterator. 
For instance my business has many tables with 100-200 fields so looking up on `_props` repeatedly is not insignificant.

The question for me is which would have a higher performance impact? Many lookups on `_props` *or* `struct` creation on each iteration?

**Comment by Nick-Lucas** [comment]
Okay so I've just profiled this and your approach will be more efficient even on something as silly as 10000 fields. So that decides it.

Dump of the profiling source attached.
[Program.cs.txt](https://github.com/Nick-Lucas/LimeBean/files/343307/Program.cs.txt)

**Comment by Nick-Lucas** [comment]
Going to merge this in now
