### ISSUE TITLE
JSON serializer returns "columns" collection, but misses properties

### ISSUE THREAD

**Issue by GeorgeHahn** [Nick-Lucas/LimeBean#28]
One thing that's really cool about RedBeanPHP is that you can basically pretend the beans are real objects. In particular, they serialize to JSON quite nicely, which allows you to return JSON objects directly from the database.

Unfortunately, LimeBean beans don't serialize well. This is an array of serialized beans, in JSON:

```js
[{"columns":["id","name"]},{"columns":["id","name"]},{"columns":["id","name"]}]
```

Do you have any suggestions on how to fix this? My initial assumption is that I need to give my JSON serializer (Newtonsoft.Json) some knowledge about Beans, but this feels heavy handed. Do you have any better ideas?

Thanks!

**Comment by Nick-Lucas** [comment]
Hey George,

I'm not a PHP developer, and also am not that familiar with Newtonsoft.JSON so apologies for any ignorance here. 

Basically you're right, you'll need to implement something yourself, but it shouldn't be too challenging as Limebean provides a simple OO approach to data access, which is how Newtonsoft.JSON is designed to work.

My suggestion would be to write a method which creates your JSON in the right format for you. You can implement the Bean class, and Limebean has support everywhere for this, so can have this functionality directly in your own `GeorgeBean` class.

The approach to get programmatic access to a Bean for serialisation might look something like this:
```C#
// pass in: IEnumerable<bean> beans
var obj = new MyNSJsonObject();
obj.Columns = beans[0].Columns;
foreach(Bean bean in beans) {
  var values = new List<object>();
  foreach(string column in bean.Columns) {
    values.Add(bean[column]);
  }
  obj.Rows.Add(values);
}
```
This should give you a Json schema like:
```json
{
  "columns": [ "id", "name" ],
  "rows": [
    [ 1, "bob" ],
    [ 2, "gill" ],
    [ 3, "jack" ]
  ]
}
```

If you're at all unsure just ping me back, and I'm very open to ideas on how we can improve this in Limebean. I've been thinking about cases we may provide some optional packages with helpers for common situations, so serialisation might be such a package.

**Comment by GeorgeHahn** [comment]
I think a custom serializer class would be the way to go for a helper package. [This link](http://blog.maskalik.com/asp-net/json-net-implement-custom-serialization/) covers the essentials.

Unfortunately, creating a magical experience with this could be tough. I'm not sure if there's a decent way to get the `[JsonConverter(typeof(WeirdNameSerializer))]` attribute onto the LimeBean class without taking a dependency on any specific serializer in the main dll. That could be messy.

**Comment by Nick-Lucas** [comment]
Yep we shouldn't introduce any internal dependency for this. Inside Limebean we should focus on providing a small API which is flexible to do anything fairly simply.

A helper package would be best under a different GitHub page & NuGet, and make use of public Limebean interfaces and inheritance options.
I would propose providing extension methods which take `Bean` and `IEnumerable<Bean>` and return sensible JSON. This fits the normal C# style for 'magical'.

Limebean should be a community effort, so if you wanted to use a namespace like `Limebean.Json` and put something out you're more than welcome, and I'll come contribute my thoughts :smile:

**Comment by Nick-Lucas** [comment]
Hi @GeorgeHahn did you make any progress on this?
Just wondering if I should close the Issue since there's nothing to do inside of Limebean.

**Comment by GeorgeHahn** [comment]
Unfortunately I won't be able to devote much time to this in the near future. Thanks for the assistance, and all the best with your project!
