### ISSUE TITLE
Traversing relations

### ISSUE THREAD

**Issue by bilogic** [Nick-Lucas/LimeBean#33]
Hi,

I'm just curious, is there anyway to traverse in LimeBean much like in redbeanphp (without writing a class for each table)? e.g. $page->book->title

Thank you.

**Comment by Nick-Lucas** [comment]
The only way I could think of is to do the lookup/query yourself with the primary & foreign keys on each table. Generally I've not used Limebean for relational structures, only for querying legacy databases one table at a time, though it's certainly possible with classes.
