### ISSUE TITLE
How ot push an branch

### ISSUE THREAD

**Issue by blackcatpolice** [Nick-Lucas/LimeBean#34]
Hi, I extension limebean, now it has dycnamic create schema by string ability. I want push it , thx~

**Comment by Nick-Lucas** [comment]
Hi there,

Happy to receive new PRs! 

Have a look at these resources for how to open a PR.

https://help.github.com/en/articles/fork-a-repo
https://help.github.com/en/articles/about-pull-requests

I'm going to close this as it's more a github question, but am interested to see what you have.
