### ISSUE TITLE
Better approach to handle gh-pages content

### ISSUE THREAD

**Issue by AlekseyMartynov** [Nick-Lucas/LimeBean#5]
Hi Nick

I have comments for the changeset https://github.com/Nick-Lucas/LimeBean/commit/d44212bbd62e08252eaeadd5a57a8468595602d4

With the current approach, when gh-pages mirrors master, it's necesary to keep branches in sync, and it might be unclear which branch to use for edits. Another negative effect is having urls like https://nick-lucas.github.io/LimeBean/appveyor.yml

A neater approach is to clean the gh-pages branch and leave only web content in it. The website source (that crazy stuff) is kept and edited in master, and the generated index.html can be easily updated via the online editor (e.g. https://github.com/Nick-Lucas/LimeBean/edit/gh-pages/index.html)

What do you think?

**Comment by Nick-Lucas** [comment]
Fantastic point, thanks!
For now it's working, but as soon as I need to make some updates I will do this so we have a single point of truth.

Many links on the site currently point to the wrong place (#2), so I'll sort both of these this week.

**Comment by Nick-Lucas** [comment]
This is now done as of 0bcd071
